-- NexoPlay V15 — additive notification/push improvements.
-- Safe to run after the notification/referral SQL already executed.

create table if not exists public.nexoplay_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_nx_push_user_v15
on public.nexoplay_push_subscriptions(user_id);

alter table public.nexoplay_push_subscriptions enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='nexoplay_push_subscriptions' and policyname='nx_push_v15_select') then
    create policy nx_push_v15_select on public.nexoplay_push_subscriptions for select using (auth.uid()=user_id or public.is_admin());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='nexoplay_push_subscriptions' and policyname='nx_push_v15_insert') then
    create policy nx_push_v15_insert on public.nexoplay_push_subscriptions for insert with check (auth.uid()=user_id);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='nexoplay_push_subscriptions' and policyname='nx_push_v15_update') then
    create policy nx_push_v15_update on public.nexoplay_push_subscriptions for update using (auth.uid()=user_id or public.is_admin()) with check (auth.uid()=user_id or public.is_admin());
  end if;
end $$;

-- Notifica al dueño del ticket cuando un moderador/admin responde.
create or replace function public.nx_notify_support_reply_v15()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  ticket_user uuid;
begin
  select user_id into ticket_user from public.support_tickets where id=new.ticket_id;
  if ticket_user is not null and new.sender_id is distinct from ticket_user then
    perform public.nx_insert_notification(
      ticket_user,
      'user',
      'support',
      '💬 Nueva respuesta de soporte',
      'Tu solicitud de soporte recibió una nueva respuesta. Entra a Nexo para leerla.',
      jsonb_build_object('ticket_id',new.ticket_id,'message_id',new.id)
    );
  end if;
  return new;
end;
$$;

do $$ begin
  if to_regclass('public.support_messages') is not null then
    execute 'drop trigger if exists nx_support_reply_v15 on public.support_messages';
    execute 'create trigger nx_support_reply_v15 after insert on public.support_messages for each row execute function public.nx_notify_support_reply_v15()';
  end if;
end $$;

-- Aviso de recarga cuando la tabla wallet_topups cambia a un estado aprobado/completado.
create or replace function public.nx_notify_wallet_topup_v15()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  obj jsonb := to_jsonb(new);
  uid uuid;
  st text;
  amount text;
begin
  begin uid := nullif(obj->>'user_id','')::uuid; exception when others then uid:=null; end;
  st := lower(coalesce(obj->>'status',obj->>'payment_status',obj->>'state',''));
  amount := coalesce(obj->>'amount',obj->>'monto','');
  if uid is not null and st in ('approved','aprobado','completed','complete','confirmed','confirmado','paid','pagado') and (tg_op='INSERT' or coalesce(to_jsonb(old)->>'status','') is distinct from st) then
    perform public.nx_insert_notification(uid,'user','wallet','💳 Recarga confirmada','Tu recarga' || case when amount<>'' then ' de S/ '||amount else '' end || ' fue confirmada.',jsonb_build_object('source_table',tg_table_name));
  end if;
  return new;
end;
$$;

do $$ begin
  if to_regclass('public.wallet_topups') is not null then
    execute 'drop trigger if exists nx_wallet_topup_v15 on public.wallet_topups';
    execute 'create trigger nx_wallet_topup_v15 after insert or update on public.wallet_topups for each row execute function public.nx_notify_wallet_topup_v15()';
  end if;
end $$;

-- Mantener notificaciones en Realtime si aún no están publicadas.
do $$ begin
  if to_regclass('public.nexoplay_notifications') is not null then
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='nexoplay_notifications') then
      alter publication supabase_realtime add table public.nexoplay_notifications;
    end if;
  end if;
exception when others then null; end $$;
