
-- NexoPlay V13 — Web Push subscriptions
create table if not exists public.nexoplay_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_nx_push_user on public.nexoplay_push_subscriptions(user_id);
alter table public.nexoplay_push_subscriptions enable row level security;
drop policy if exists "nx_push_owner_select" on public.nexoplay_push_subscriptions;
create policy "nx_push_owner_select" on public.nexoplay_push_subscriptions
for select using (auth.uid() = user_id);
drop policy if exists "nx_push_owner_insert" on public.nexoplay_push_subscriptions;
create policy "nx_push_owner_insert" on public.nexoplay_push_subscriptions
for insert with check (auth.uid() = user_id);
drop policy if exists "nx_push_owner_update" on public.nexoplay_push_subscriptions;
create policy "nx_push_owner_update" on public.nexoplay_push_subscriptions
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
