-- NexoPlay V14 — Notifications for every user + admin + realtime + push subscriptions
create table if not exists public.nexoplay_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_nx_push_user on public.nexoplay_push_subscriptions(user_id);
alter table public.nexoplay_push_subscriptions enable row level security;
drop policy if exists "nx_push_owner_select" on public.nexoplay_push_subscriptions;
create policy "nx_push_owner_select" on public.nexoplay_push_subscriptions for select using (auth.uid() = user_id);
drop policy if exists "nx_push_owner_insert" on public.nexoplay_push_subscriptions;
create policy "nx_push_owner_insert" on public.nexoplay_push_subscriptions for insert with check (auth.uid() = user_id);
drop policy if exists "nx_push_owner_update" on public.nexoplay_push_subscriptions;
create policy "nx_push_owner_update" on public.nexoplay_push_subscriptions for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table public.nexoplay_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  audience text not null default 'user' check (audience in ('user','admin')),
  type text not null default 'info',
  title text not null,
  message text not null,
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists idx_nx_notify_user_created on public.nexoplay_notifications(user_id, created_at desc);
create index if not exists idx_nx_notify_audience_created on public.nexoplay_notifications(audience, created_at desc);
alter table public.nexoplay_notifications enable row level security;
drop policy if exists "nx_notify_select" on public.nexoplay_notifications;
create policy "nx_notify_select" on public.nexoplay_notifications for select using ((audience='user' and auth.uid()=user_id) or (audience='admin' and public.is_admin()));
drop policy if exists "nx_notify_update" on public.nexoplay_notifications;
create policy "nx_notify_update" on public.nexoplay_notifications for update using ((audience='user' and auth.uid()=user_id) or (audience='admin' and public.is_admin())) with check ((audience='user' and auth.uid()=user_id) or (audience='admin' and public.is_admin()));

do $$ begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='nexoplay_notifications') then
    alter publication supabase_realtime add table public.nexoplay_notifications;
  end if;
exception when others then null; end $$;

create or replace function public.nx_insert_notification(
  p_user_id uuid, p_audience text, p_type text, p_title text, p_message text, p_data jsonb default '{}'::jsonb
) returns bigint language plpgsql security definer set search_path=public as $$
declare rid bigint;
begin
  insert into public.nexoplay_notifications(user_id,audience,type,title,message,data)
  values(p_user_id,coalesce(p_audience,'user'),coalesce(p_type,'info'),p_title,p_message,coalesce(p_data,'{}'::jsonb)) returning id into rid;
  return rid;
end $$;

-- Customer: order created
create or replace function public.nx_notify_order_created() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.user_id is not null then
    perform public.nx_insert_notification(new.user_id,'user','purchase','🛍️ Compra recibida','Tu pedido '||coalesce(new.order_code,'')||' fue registrado correctamente. Te avisaremos cuando esté listo.',jsonb_build_object('order_id',new.id,'order_code',new.order_code));
  end if;
  perform public.nx_insert_notification(null,'admin','purchase','🛒 Nueva compra','Se registró una nueva compra: '||coalesce(new.order_code,'sin código')||'.',jsonb_build_object('order_id',new.id,'order_code',new.order_code,'user_id',new.user_id));
  return new;
end $$;
drop trigger if exists nx_order_created on public.nexoplay_orders;
create trigger nx_order_created after insert on public.nexoplay_orders for each row execute function public.nx_notify_order_created();

-- Customer + admin: ticket created
create or replace function public.nx_notify_ticket_created() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.user_id is not null then
    perform public.nx_insert_notification(new.user_id,'user','support','🆘 Ticket creado','Tu solicitud de soporte fue recibida correctamente.',jsonb_build_object('ticket_id',new.id));
  end if;
  perform public.nx_insert_notification(null,'admin','support','🆘 Nuevo ticket','Un cliente creó una nueva solicitud de soporte.',jsonb_build_object('ticket_id',new.id,'user_id',new.user_id));
  return new;
end $$;
drop trigger if exists nx_ticket_created on public.support_tickets;
create trigger nx_ticket_created after insert on public.support_tickets for each row execute function public.nx_notify_ticket_created();

-- VIP: referral request
create or replace function public.nx_notify_referral_created() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.vip_owner_user_id is not null then
    perform public.nx_insert_notification(new.vip_owner_user_id,'user','referral','👑 Nueva solicitud','Un usuario solicitó Distribuidor usando tu código. Revisa el Panel de Referidos.',jsonb_build_object('request_id',new.id,'user_id',new.user_id));
  end if;
  perform public.nx_insert_notification(null,'admin','referral','🤝 Nueva solicitud de referido','Hay una nueva solicitud para revisión.',jsonb_build_object('request_id',new.id));
  return new;
end $$;
drop trigger if exists nx_referral_created on public.nexoplay_vip_referral_requests;
create trigger nx_referral_created after insert on public.nexoplay_vip_referral_requests for each row execute function public.nx_notify_referral_created();

-- Customer: order delivered
create or replace function public.nx_notify_order_status() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if coalesce(old.delivery_status,'') is distinct from coalesce(new.delivery_status,'') and lower(coalesce(new.delivery_status,''))='delivered' and new.user_id is not null then
    perform public.nx_insert_notification(new.user_id,'user','delivery','📦 Pedido listo','Tu pedido '||coalesce(new.order_code,'')||' ya fue entregado. Revisa tus compras.',jsonb_build_object('order_id',new.id,'order_code',new.order_code));
  end if;
  return new;
end $$;
drop trigger if exists nx_order_status on public.nexoplay_orders;
create trigger nx_order_status after update on public.nexoplay_orders for each row execute function public.nx_notify_order_status();
